### ISSUE TITLE
no package.json

### ISSUE THREAD

**Issue by matthias-maier** [Matzefication/MMM-Hello-Mirror#1]
Hi. Did you forget to commit the package.json file in root directory? It is noch possible to use npm install ;-)

**Comment by Matzefication** [comment]
Hello,

like written in the readme no npm install is needed because there are no dependencies to other packages.

Greets

**Comment by matthias-maier** [comment]
Oh. By installing a few modules I did not read the "not" in your installation guide. Thanks!
